export const ADD_INPUT_VALUE = `ADD_INPUT_VALUE`
export const DELETE_INPUT_VALUE = `DELETE_INPUT_VALUE`
export const EXPLANATION_FIELD_TOGGLE = `EXPLANATION_FIELD_TOGGLE`
export const MODAL_HIDE = `MODAL_HIDE`
export const MODAL_SHOW = `MODAL_SHOW`
export const SET_COLUMN = `SET_COLUMN`
export const SET_COLUMN_TITLE = `SET_COLUMN_TITLE`
export const SET_INPUT_TYPE = `SET_INPUT_TYPE`
