export const MODAL_HIDE = `MODAL_HIDE`
export const MODAL_SHOW = `MODAL_SHOW`
export const REMOVE_LEARN_GOAL = `REMOVE_LEARN_GOAL`
export const RESET_LOGBOOK = `RESET_LOGBOOK`
export const SAVE_LOGBOOK = `SAVE_LOGBOOK`

// General page
export const ADD_LOGBOOK_PERIOD = `ADD_LOGBOOK_PERIOD`

// Column page
export const ADD_LEARN_GOAL = `ADD_LEARN_GOAL`
export const ADD_INPUT_OPTION = `ADD_INPUT_OPTION`
export const DELETE_INPUT_OPTION = `DELETE_INPUT_OPTION`
export const EXPLANATION_FIELD_TOGGLE = `EXPLANATION_FIELD_TOGGLE`
export const SET_COLUMN = `SET_COLUMN`
export const SET_COLUMN_TITLE = `SET_COLUMN_TITLE`
export const SET_EXPLANATION = `SET_EXPLANATION`
export const SET_INPUT_TYPE = `SET_INPUT_TYPE`

// Goals page
export const POST_IMAGE = `POST_IMAGE`
export const SET_GOAL = `SET_GOAL`
export const SET_GOAL_DESCRIPTION = `SET_GOAL_DESCRIPTION`
export const SET_GOAL_IMAGE = `SET_GOAL_IMAGE`
export const SET_GOAL_POSITION = `SET_GOAL_POSITION`
export const SET_GOAL_TITLE = `SET_GOAL_TITLE`
