export const GET_YEARS = 'GET_YEARS'
export const GET_ACTIVE_LOGBOOK = 'GET_ACTIVE_LOGBOOK'
export const UPDATE_CURRENT_PHASE = 'UPDATE_CURRENT_PHASE'
export const UPDATE_ACTIVE_GOAL = 'UPDATE_ACTIVE_GOAL'
