export const GET_YEARS = 'GET_YEARS'
export const GET_ACTIVE_LOGBOOK = 'GET_ACTIVE_LOGBOOK'
export const UPDATE_LOGBOOK = 'UPDATE_LOGBOOK'
export const UPDATE_LOGBOOK_SUCCESS = 'UPDATE_LOGBOOK_SUCCESS'
