export const GET_LOGBOOK = `GET_LOGBOOK`
export const GET_LOGBOOK_ID = `GET_LOGBOOK_ID`
export const GET_LOGBOOK_GROUP_ANSWERS = `GET_LOGBOOK_GROUP_ANSWERS`
export const GET_LOGBOOK_GROUP_OVERVIEW = `GET_LOGBOOK_GROUP_OVERVIEW`
